import Navbar from "@/app/components/view/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter, Maven_Pro } from "next/font/google";
import Wrapper from "@/app/components/shared/Wrapper";
import { NavbarMenuProvider } from "@/app/store/NavbarMenuContext";

const inter = Maven_Pro({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Wrapper>
          <NavbarMenuProvider>
            <Navbar />
          </NavbarMenuProvider>
          {children}
        </Wrapper>
      </body>
    </html>
  );
}
